POST http://localhost:3000/auth/register
Content-Type:application/json
{
    "firstName":"Miss",
    "lastName":"Susan",
    "email":"susan@mail.com",
    "password":"secret",
    "role":"instructor",
    "profilePicture":"google.com"
}