GET http://localhost:3000/course/enrolled-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFmZTJhNjNkNzQ4OGM1MjhhOTgzNGEiLCJ1c2VybmFtZSI6IlBldGVyIERvZSIsImVtYWlsIjoicGV0ZXJAbWFpbC5jb20iLCJyb2xlIjoiaW5zdHJ1Y3RvciIsImlhdCI6MTc2NDEyMjc4MywiZXhwIjoxNzY0MTI2MzgzfQ.cSPYc06iIQnKsVWF7DtVPU2jjx5NlEO2hpO4zHQ05fg