POST http://localhost:3000/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFmZTJhNjNkNzQ4OGM1MjhhOTgzNGEiLCJ1c2VybmFtZSI6IlBldGVyIERvZSIsImVtYWlsIjoicGV0ZXJAbWFpbC5jb20iLCJyb2xlIjoiaW5zdHJ1Y3RvciIsImlhdCI6MTc2NDQ5ODU4NywiZXhwIjoxNzY0NTAyMTg3fQ.dNDEMCa1xYBkPVWlaUgPa33QC_1lypmotDE7DuraL-Y
Content-Type:application/json
{
    "course_id":"691fe3e03d7488c528a98353",
    "stars":"1",
    "comment":"Best"
}