GET http://localhost:3000/course/update-course-status/691fe3133d7488c528a9834f?status=approved
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTFmZTJjNjNkNzQ4OGM1MjhhOTgzNGMiLCJ1c2VybmFtZSI6ImFkbWluIHVuZGVmaW5lZCIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjM5NTQ4NjAsImV4cCI6MTc2Mzk1ODQ2MH0.GWBH2F-grAAlZsN4W1J3wl8nqZUMgEFBwIyjOodcNtU